steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/tm-group-2a9a5/screen-leap:$REVISION_ID", "."]

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/tm-group-2a9a5/screen-leap:$REVISION_ID"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute', 'ssh', 'tuannguyen@tm-loyalty-development', '--zone=asia-east2-c',
      '--command=docker pull gcr.io/tm-group-2a9a5/screen-leap:$REVISION_ID && docker service update --image gcr.io/tm-group-2a9a5/screen-leap:$REVISION_ID --with-registry-auth internal_api_service_internal_store'
    ]
